### ISSUE TITLE
Phylo submodule review and roadmap

### ISSUE THREAD

**Issue by Blahah** [BioJulia/Bio.jl#13]
Phylo code review - 20th April 2014
----

### General notes

Overall very good, and a great start for the Bio.jl phylo module. Here I have attempted to map out what would be required to get to a version 1, high quality phylogenetics module to ship with Bio.jl that covers the major use cases.

This review covers:

1. the API
2. design of the module
3. minor style points
4. testing
5. repetition
6. documentation

Most of the review is a to-do list, so that as points are addressed they can be checked off.

### 1. API

Currently there are methods for the following operations on trees:

- parsing/lexing newick format
- parsing/lexing PhyloXML (in progress)
- getting the root node
- getting the children of all nodes in a tree simultaneously
- test whether two trees are equal
- produce a unique hash from a tree

We should define the minimal API for this library. I suggest it should include (in addition to the existing functionality):

#### Node/tree manipulation

- [x] get and set any property of a node
- [x] add child nodes
- [x] add sibling nodes
- [x] remove child nodes
- [x] delete nodes (with or without connecting their descendents to the parent)
- [x] detach the node (delete it from the original tree and return it as a new tree)
- [x] re-root a (sub)tree

#### Tree exploration

- [x] get the children of a node
- [x] check if the node is a leaf (has no children)
- [x] get the parent of a node
- [x] check if the node is root
- [x] get the siblings of a node
- [x] get all the descendents of a node
- [x] get all the leaves of a (sub)tree (i.e. all terminal descendents of a node)
- [x] depth-first search of a (sub)tree
- [x] breadth-first search of a (sub)tree

#### Tree measurement

- [x] Get the shortest path between two nodes
- [x] Get the distance (aggregate branch length) between two nodes
- [ ] Check whether a (sub)tree is monophyletic for a given taxonomic rank
- [x] Find the midpoint outgroup

#### Tree visualisation

- [ ] print a text representation
- [ ] print an image representation
- [ ] produce an interactive representation
- [ ] annotate these visualisations with arbitrary information from the tree

#### IO

- [ ] parse/lex nexus
- [ ] parse/lex NexML

### 2. Design

The module is structured around the abstract type `Phylogeny`, representing a phylogeny. It has subtypes Clado and Phylo representing Cladograms and Phylograms respectively.

These types represent the tree as an adjacency list with associated arrays of properties such as node names and edge lengths.

I would like to query two aspects of this design:

1. For many of the features listed above as desirable to include in the API, a natural representation of trees is as heirarchies of nodes. In this format, a variable containing a tree is really a pointer to the root node, which knows that it is a root and what its children are. Each child node knows it parent, might know how long the branch is from its parent, and knows what its children are. This is how the tree representations in BioPython/ETE and BioRuby work. Benefits of this system are that it is very easy to insert or remove parts of a tree, split a tree into subtrees, and recursively represent a tree in a text format. I can't think of any downsides (but happy to be corrected). We should consider adopting this representation unless there are major constraints on doing so in Julia.
2. Is it necessary to have separate Cladogram and Phylogram types? It seems to me that a Cladogram is easily represented by a tree where each node has a null branch length. A method on the root node could tell us whether the tree is a cladogram.

I think these two queries should be resolved before any of the remaining sections are addressed.

### 3. Style points

- [x] Method names should be consistent with one another and with the Standard Library. STL uses "$(verb)$(noun)", e.g. `joinpath`. `readtree` is consistent whereas `treebuild` and `treewrite` are not. Should be `buildtree` and `writetree`. Similarly, `cladobuild` should be `buildclado`, etc.
- [x] Why are file paths restricted to being `ASCIIStrings`? I think all operating systems now allow unicode paths. If this is true, we should be more liberal with the `String` type we allow.
- [x] Style guide suggests variables should be all lower case, with underscore separators if absolutely necessary. We have, e.g. `nodeLabel`, `tipLabel`, `treeNames`, etc. These should be moved to all-lowercase.
- [x] Style guide suggests function names should be lowercase - the names of  internal functions of `cladobuild`, `treebuild`, `newick`, etc. should be lowercased. e.g. `AddInteral` -> `addinternal`.

### 4. Testing

Test coverage is quite good - around 95% of the code is hit in tests. `--code-coverage` shows one constructor and several parts of functions that are not covered - in particular conditional statements inside large functions. We should aim for 100% coverage.

- [x] ReducedTopology is not tested.
- [x] In `cladobuild`, the conditional block (`if search(tp, ",") == 0:-1`) to handle the case where a tree has no commas is not tested.
- [x] In `GoDown`, the same conditionl block (`if search(tp, ",") == 0:-1`) is not tested.
- [x] In `treewrite`, the case where `append == true` is not tested.
- [x] In `newick`, the conditional `if j > N` is not tested.
- [x] In `addTerminal`, the case where `name == false` is not tested.

### 5. Repetition

- [x] There is some code repetition in the multiple versions of the `build` methods. Eliminating repetition by moving repeated code to functions makes maintenance easier and reduces method complexity. Functions or blocks that are either completely or mostly repeated should be broken out into functions with higher scope so all methods with the shared code can call them.
- [x] `AddInternal` is exactly the same in `cladobuild` and `treebuild`.
- [x] could `treewrite` for the case of a single tree simply add the single tree to an array and call the `Array` version?
- [x] the two versions of `newick()` share a lot of code

### 6. Documentation

Currently, the documentation is in the form of comments on the main functions. This is sufficient to use the code, but we should expand this to full standalone documentation for all types, functions and methods and a tutorial highlighting common use-cases.

**Comment by dcjones** [comment]
@Ward9250 Should we keep this issue open, or is it redundant with #17?

**Comment by Ward9250** [comment]
I thin this is ok to close. Because this was a review of the very first pass at a Phylo module. And the current one is now waaaaay different to the original.
