### ISSUE TITLE
Genotype Count Matrices for Population Genetics

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/Bio.jl#160]
In population genetics we desire matrix-like types which allow us to store genotypic data in a convenient format which permits efficient computation of population genetics summaries or other statistics. E.g. The frequency of an allele in a population and so on. Here we discuss implementation and design.
# Basic Design

The basic design of the matrix will be a matrix, where rows represent individuals and columns represent the alleles, such that one gene might have 3 columns if it has 3 distinct alleles of that gene. 

Furthermore, individuals may be grouped into populations. So you should be able to do things like:

`my_matrix[:, :GeneA]` or `my_matrix[Ind(:Mouse), :]` or `my_matrix[Pop(:Norwich), :]`

To select entire genes, individuals, or populations.

To this end, indexing data structures which create Integer indexes based on names (symbols) have been implemented, and will be merged into Bio in Bio.Indexing as a separate PR.
# TODO
- [x] Merge Indexing datastructures.
- [ ] Create basic type for the count matrices.
- [ ] IO for the most common formats.

**Comment by Ward9250** [comment]
# Basic Design

The basic design of the matrix will be a matrix, where rows represent individuals and columns represent the alleles, such that one gene might have 3 columns if it has 3 distinct alleles of that gene. 

Furthermore, individuals may be grouped into populations. So you should be able to do things like:

`my_matrix[:, :GeneA]` or `my_matrix[Ind(:Mouse), :]` or `my_matrix[Pop(:Norwich), :]`

To select entire genes, individuals, or populations.

To this end, indexing data structures which create Integer indexes based on names (symbols) have been implemented, and will be merged into Bio in Bio.Indexing as a separate PR.

**Comment by Ward9250** [comment]
#161 has been created. Comments on it are welcome. There is some functionality I would like to add to the indexes (mostly for phylo) to do with pushing new label-value associations. or removing specific ones, or reassigning them (removing tree nodes, adding tree nodes, and pruning and grafting trees and such! - but that's a separate issue to this).

**Comment by Ward9250** [comment]
#161 is now merged. Indexers can be used with the types planned here and in Phylo.
