### ISSUE TITLE
EU Codefest to-do list

### ISSUE THREAD

**Issue by Blahah** [BioJulia/Bio.jl#22]
## Bio.Phylo

- [x] Finish working through [code review](https://github.com/BioJulia/Bio.jl/issues/13) (@Ward9250)
- [x] [PhyNode constructors](https://github.com/Ward9250/Bio.jl/blob/Ward9250PhyloV1/src/phylo/typedefs.jl#L33-L66): rename `label` to `name` (@Ward9250)
- [x] Full tests (@Blahah)
- [ ] Consider making Trees inherit from Graphs (both)
- [x] All functions inline documented (@Blahah)
- [ ] Getting started tutorial (@Blahah)
- [ ] iJulia notebook walk-through demonstration (both)

**Comment by dcjones** [comment]
Is this ok to close?

**Comment by Blahah** [comment]
Yes, although the last 2 items should be separate issues
