### ISSUE TITLE
IO interface cleanup

### ISSUE THREAD

**Issue by kdmurray91** [BioJulia/Bio.jl#288]
In several threads across issues and gitter recently @Ward9250, @bicycle1885 and I have discussed improvements that could be made to the design and consistency of the IO interfaces of parsers and writers. A rough summary of these ideas follows.
- [x] Change open argument order such that types come first (@vchuravy)
- [ ] Supporting `open(::Type{FMT}, io::IO)` 
- [x] Defining a `stream{T<:AbstractParser}(parser::T)` function to retrieve the underlying IO object (or BufferedIOStream, or BGZFStream etc) from a parser or writer. EDIT: Done in #292 
- [x] Using the `stream(parser)` function to automatically define standard IOStream operations like `eof()`, `flush()`, `close()`, `write()`, etc. in a unified way. EDIT: Done in #292 
- [x] Parser -> Reader: Done in #290

**Comment by bicycle1885** [comment]
Sorry for wandering off the topic a little bit, but I'd like to know how you feel about renaming `XXXParser`s to `XXXReader`s. Since we have *writer*s to serialize data into a formatted file, I think having corresponding *reader*s will be more symmetric.

**Comment by vchuravy** [comment]
How about using `open(::Type, filename)` as an interface?

**Comment by kdmurray91** [comment]
@vchuravy Why? I'm quite new to Julia, is that a more common pattern? I guess that is how one does e.g. `zeros(Int8, (2, 3))`.

**Comment by Ward9250** [comment]
:+1: for Readers.

**Comment by bicycle1885** [comment]
> Allowing open() do file; ...; end; style "context managers" (excuse the python) by defining open(fn::Function, args..., ::Type{FMT})

I think the last item is not needed because `Base.open` already implements a `open(f::Function, args...)` method.

**Comment by bicycle1885** [comment]
One more proposal I have in my mind for a long time is removing the format types (e.g. `FASTA`) and using reader/writer types directly or indirectly by wrapping it with `open`. Taking @vchuravy's suggestion into account, creating a reader object looks like:
```julia
# direct call
reader = FASTAReader("hg38.fa")
# indirect call
reader = open(FASTAReader, "hg38.fa")
```

**Comment by Ward9250** [comment]
I think that would be ok.

**Comment by vchuravy** [comment]
@kdmurray91 @bicycle1885 

The style `f(::Type, args...)` is as far as I know a quite common pattern and the closet cousin would be `parse(::Type, String)` in Base.

**Comment by kdmurray91** [comment]
@vchuravy OK, sounds like we should do that then. Added to checklist

**Comment by bicycle1885** [comment]
`open(::Type{FMT}, io::IO)` looks slightly odd because it opens nothing (`io` must be opened before calling it).  So I think the following definitions would be enough (FASTA as an example):
```julia
open(::Type{FASTAReader}, filepath::AbstractString)
open(::Type{FASTAWriter}, filepath::AbstractString; append::Bool=false)
FASTAReader(filepath::AbstractString)
FASTAReader(stream::IO)
FASTAWriter(filepath::AbstractString; append::Bool=false)
FASTAWriter(stream::IO)
```

**Comment by bicycle1885** [comment]
If you think the interfaces I proposed above look good, I'll start working on it.

**Comment by kdmurray91** [comment]
Sounds great @bicycle1885. The `open(FMT, io::IO)` was written before your suggestion to make `FastaReader()` etc.

**Comment by kdmurray91** [comment]
I think this is done and closeable, right @Ward9250 & @bicycle1885 ?

**Comment by bicycle1885** [comment]
Yes, I believe.
